### ISSUE TITLE
How to set the text color of the ruler

### ISSUE THREAD

**Issue by imsole** [daybrush/ruler#1]
look picture ⬇️⬇️⬇️
![image](https://user-images.githubusercontent.com/3367457/70846208-fb188200-1e91-11ea-9e69-442a24f77a8e.png)

**Comment by daybrush** [comment]
@imsole 

oh sorry. I'll add props for textColor soon.

**Comment by daybrush** [comment]
@imsole 


ruler is released.

@scena/ruler@0.2.0
@scena/react-ruler@0.2.0
preact-ruler@0.2.0
ngx-ruler@0.2.0
vue-ruler@0.2.0
svelte-ruler@0.2.0


you can use `textColor` props.

**Comment by imsole** [comment]
good job! 👍
