### ISSUE TITLE
Vertical rule grow infinite !

### ISSUE THREAD

**Issue by djmisterjon** [daybrush/ruler#11]
I think the `vertical` rule have some bug ? it seem grow infinitely when is compute rendering!
Horizontal work fine !

here preview gif
![s4g4wheeabwsa3rf3fg3aga2552223](https://user-images.githubusercontent.com/24865815/87232907-be155f00-c390-11ea-9be5-92222fabcf0a.gif)
code used in my projet look like this
ps:i also try many css styles, without success.
```jsx
const Camera = ({ children }) => {
	const pos = store({
		x: 0,
		y: 0,
	});
	return (
		<>
	<Box
			className='content'
			bgcolor='grey.700'
			display='flex'
			justifyContent='top'
			flexDirection='column'
			style={{ minWidth: '100%', width: 0, minHeight: '100%', height: 0 }}
		>
			<Box bgcolor='grey.200'>
				<div className='Ruler' style={{ width: '100%', height: '24px' }}>
					<Ruler type='horizontal' scrollPos={pos.x} />
				</div>
			</Box>
			<Box
				className='content'
				bgcolor='grey.700'
				display='flex'
				justifyContent='top'
				flexDirection='row'
				flexGrow={1}
			>
				<Box m={0.5} display='flex' bgcolor='grey.200'>
					<div className='Ruler' style={{ width: '28px' }}>
						<Ruler type='vertical' scrollPos={pos.y} />
					</div>
				</Box>
				<Box flexGrow={1} bgcolor='grey.200'>
					<TransformWrapper
						options={{
							limitToBounds: true,
							limitToWrapper: true,
							minScale: 1,
							maxScale: 2,
						}}
						onPanning={(e) => {
							pos.x = e.positionX;
							pos.y = e.positionY;
						}}
					>
						<TransformComponent>
							<div>Camera:</div>
							<div>{children}</div>
						</TransformComponent>
					</TransformWrapper>
				</Box>
			</Box>
		</Box>
		</>
	);
};
export default view(Camera);
```

is this a know issue ? 
or if you want i can take time to make you a demo ?
thanks again

**Comment by daybrush** [comment]
@djmisterjon 

Can you show the other styles of canvas and the styles applied to the Ruler class?

**Comment by djmisterjon** [comment]
do you mean the parent style ?
![image](https://user-images.githubusercontent.com/24865815/87233393-fae35500-c394-11ea-83eb-42e55b7bc586.png)

i think the issue stat here with flexbox
![image](https://user-images.githubusercontent.com/24865815/87233411-2c5c2080-c395-11ea-805a-38b717c9a13f.png)
if i remove `<Ruler type='vertical' scrollPos={pos.y} />`
i get no more infinite grow.

**Comment by daybrush** [comment]
@djmisterjon 

I want know style of `<div className="Ruler">`.

**Comment by djmisterjon** [comment]
> @djmisterjon
> 
> I want know style of `<div className="Ruler">`.

ho sorry for this, it is empty, I had put it to prepare myself, but it is empty for the moment.

**Comment by daybrush** [comment]
@djmisterjon 

How about Muibox-root-58?

**Comment by daybrush** [comment]
@djmisterjon 
I would really appreciate it if you did. It does not reproduce well.

**Comment by djmisterjon** [comment]
> @djmisterjon
> I would really appreciate it if you did. It does not reproduce well.

ok here 
https://codesandbox.io/s/sparkling-pond-s3wzq?file=/src/ruler.js
the file `app.js` **are not important.**

Look in `ruler.js` , is where i create the FrontEnd skeleton for the app and embed the box with camera and your ruler.
At line `34` you can see the issue, i also add you a comment.
I hope is not my fault and waste your time :)

**Comment by djmisterjon** [comment]
you can also click on this to debug in new window context , if is your first time on Codesandbox :)
![image](https://user-images.githubusercontent.com/24865815/87234161-49482200-c39c-11ea-9c36-3ab814bd7518.png)

**Comment by daybrush** [comment]
@djmisterjon 

Add
```css
height: calc(100% - 24px);
```

to Muibox-root-18

**Comment by djmisterjon** [comment]
ho !!! thanks for this solution, i would never think about it by myself.
Work fine !!!
Thank you so much for your precious time friend !
