### ISSUE TITLE
Is there any documentation on react?

### ISSUE THREAD

**Issue by o0Chivas0o** [daybrush/ruler#15]
## Environments
* Framework name:
* Framework version:
* Component name: 
* Component version:
* Testable Address(optional):

**Comment by daybrush** [comment]
@o0Chivas0o 

Refer to the README and API documentation

https://daybrush.com/ruler/release/latest/doc/

**Comment by o0Chivas0o** [comment]
> @o0Chivas0o
> 
> Refer to the README and API documentation
> 
> https://daybrush.com/ruler/release/latest/doc/

thanks!
