### ISSUE TITLE
Ability to customize number (and size of) ticks?

### ISSUE THREAD

**Issue by joncursi** [daybrush/ruler#18]
## Environment

* Framework name: `react`
* Framework version: `17.0.2`
* Component name: `@scena/react-ruler`
* Component version: `0.7.3`

## Description

Using [your suggestion](https://github.com/daybrush/ruler/issues/2#issuecomment-579688615), we were able to get our rulers to render in inches rather than pixels. However, the number of ticks (and size of the ticks) is not intuitive to the user, because each inch is being divided into 10ths (10 slices), rather than 8ths (8 slices) or 16ths (16 slices).

Current display:

![image](https://user-images.githubusercontent.com/4974609/120393777-7da03600-c300-11eb-969d-6383d329fc30.png)

Desired display:

![download](https://user-images.githubusercontent.com/4974609/120394248-26e72c00-c301-11eb-9a64-0c93f10d71ac.png)

Is it possible to customize the number (and size of) the ticks?

**Comment by daybrush** [comment]
@joncursi 

Displaying text every tick is not supported. I will consider it in the next version.

**Comment by joncursi** [comment]
@daybrush sorry, I'm actually not looking for text on every tick. Please ignore the fractions on the above screenshot. I'm moreso looking for the ability to customize the number of ticks in between the text. So if I have `0`, `1`, `2`, ..., representing 1 inch measurements, I want to have 8 or 16 segments in between each, rather than 10 which is the current behavior.

**Comment by daybrush** [comment]
@joncursi 

do you mean like this?

https://codesandbox.io/s/strange-tdd-98g2y?file=/src/App.tsx

However, I will add line breaks and font size settings in the next function.

**Comment by joncursi** [comment]
@daybrush i don't see a difference between existing behavior and what is shown in the code sandbox. There are still 10 segments between each text reading, and I am trying to adjust that to 8:

![Screen_Shot_2021-06-06_at_7_15_14_PM](https://user-images.githubusercontent.com/4974609/120943256-cc344280-c6fb-11eb-8ec8-928935a2da29.jpg)

**Comment by daybrush** [comment]
@joncursi 

 `@scena/react-ruler@0.8.1` is released.
segment prop is added.

set segment prop to 8
```jsx
<Ruler
  segment={8} /> 

```

**Comment by joncursi** [comment]
Nice! Will this feature also work if I’m using rulers through the “guides” package?

**Comment by daybrush** [comment]
@joncursi 

The guides have also been updated. Check it

**Comment by joncursi** [comment]
👍  thank you!
