### ISSUE TITLE
Bug with throttle drag used on group moveable

### ISSUE THREAD

**Issue by gaterin** [daybrush/ruler#20]
Bug with throttle drag used on group moveable

throttle drag works well when only 1 item is moveable
but when you use Group+Moveable+ throttledrag, the throttle does not work well

I tested the code also on your StoryBook, same results

throttleDrag = 25px

see this gif for the bug

PS: Amazing work!

![bug_group_moveable_plus_thottle_drag](https://user-images.githubusercontent.com/26376464/138846626-5b8c13d5-dafb-4707-9d59-0e007904888a.gif)

**Comment by daybrush** [comment]
@gaterin 
https://github.com/daybrush/moveable/issues/542
