### ISSUE TITLE
how to set a max value of the ruler?

### ISSUE THREAD

**Issue by Feafortecsy** [daybrush/ruler#23]
## Environments
* Framework name:  react
* Framework version: 17.0.1
* Component name: @scena/react-ruler
* Component version: 0.8.1
* Testable Address(optional): https://codesandbox.io/s/great-leaf-0ry7r?file=/src/App.tsx

## Description

such as **set 24:00 or an other timestamp as the max**, Stop scrolling or dragging to the right when it reaches its maximum value, how can i get that.

**Comment by daybrush** [comment]
@Feafortecsy 

@scena/react-ruler 0.9.1 is released.

Use `range`prop. (`range={[0, 100]}`
