### ISSUE TITLE
how can we draw this style ruler?

### ISSUE THREAD

**Issue by leeboo** [daybrush/ruler#3]
![image](https://user-images.githubusercontent.com/1256745/75226853-0a983d80-57e8-11ea-948f-aa9c216b857b.png)
thanks

**Comment by hmmhmmhm** [comment]
did you makes it? or you need some example?

**Comment by leeboo** [comment]
> did you makes it? or you need some example?

i need some examples,
the default style like this:
![image](https://user-images.githubusercontent.com/1256745/75229510-015d9f80-57ed-11ea-8675-4e72db65b393.png)
how can we reverse the line

thanks

**Comment by daybrush** [comment]
```js
backgroundColor?: string;
lineColor?: string;
textColor?: string;
```
use this color.
```js
backgroundColor: white
lineColor: black
textColor: black
```

**Comment by leeboo** [comment]
![image](https://user-images.githubusercontent.com/1256745/76041296-acf4b580-5f8c-11ea-8b0e-9750bfa78364.png)

**Comment by daybrush** [comment]
@leeboo 

new version is release. use direction props. (default: "end")

You can direction props to "start"

```js
direction: "start"
```

**Comment by leeboo** [comment]
> @leeboo
> 
> new version is released. use direction props. (default: "end")
> 
> You can direction props to "start"
> 
> ```js
> direction: "start"
> ```

amazing
thanks
