### ISSUE TITLE
ngx-ruler type issues

### ISSUE THREAD

**Issue by RobinKamps** [daybrush/ruler#33]
## Description
cannot build latest ngx-ruler, mainly because it cant find/reolve @scena/ruler
 error TS2307: Cannot find module '@scena/ruler' or its corresponding type declarations.

**Comment by daybrush** [comment]
@RobinKamps 

ngx-ruler's new version is released. (0.12.1)  Check it again.

**Comment by RobinKamps** [comment]
It is working. Thank you!
