### ISSUE TITLE
Highlight  selected elements or canvas dimmensions

### ISSUE THREAD

**Issue by vlodkopits** [daybrush/ruler#35]
## Environments
* Framework name: angular
* Framework version:
* Component name: Ruler
* Component version: latest
* Testable Address(optional): 

## Description
How can I make something like this?
![image](https://user-images.githubusercontent.com/14543503/210607754-6ef2d6e0-28f0-4863-b3b3-44ebef14d927.png)
or this 
![image](https://user-images.githubusercontent.com/14543503/210607815-b2d3198f-b2aa-4389-b404-308d14de23d4.png)

how to highlight in different color selected object or canvas size

**Comment by daybrush** [comment]
@vlodkopits 

okay. I'll add it soon.

**Comment by daybrush** [comment]
@vlodkopits 

ruler's new version is released.

`selectedRanges`, `selectedBackgroundColor`(default: "#555555") props were added.


```js
[selectedRanges]="[[100, 300]]"
selectedBackgroundColor="#555555"
```

**Comment by vlodkopits** [comment]
thanks! work well.

**Comment by daybrush** [comment]
@vlodkopits  @bytasv 

Ruler, Guides ' new version are released. Check it again.

Thank you :0
