### ISSUE TITLE
Feature: Canvas scale option

### ISSUE THREAD

**Issue by SidIcarus** [daybrush/ruler#36]
## Environments
* Framework name: VanillaJS
* Component name: Ruler
* Component version: 0.12.2 

## Description
Allow for `context.scale(x, y);` to be customized.
It currently is hardcoded to `context.scale(2, 2);`.

I have found that changing it from `1` to `3` based on whether it is a high density screen or not to be helpful between monitors.

```js

function isHighDensity () {
  let isHighDensity = false
  if (window.matchMedia) {
    const mq = window.matchMedia('only screen and (min--moz-device-pixel-ratio: 1.3), only screen and (-o-min-device-pixel-ratio: 2.6/2), only screen and (-webkit-min-device-pixel-ratio: 1.3), only screen  and (min-device-pixel-ratio: 1.3), only screen and (min-resolution: 1.3dppx)')
    isHighDensity = mq && mq.matches
  }

  return isHighDensity || window.devicePixelRatio > 1
}

const rulerScale = isHighDensity() ? 3 : 1

...

context.scale(rulerScale, rulerScale);
```

Another thing I have found to help with the rendering is to force antialiasing of the canvas by using subpixeling. The `x` position of the tick can be offset by `.5 + (isHorizontal ? -1 : 1)` to enable it. Might be worth exploring.

**Comment by daybrush** [comment]
@SidIcarus 

ruler's new version is released.

My 1st monitor's devicePixelRatio is 2 and my 2nd's is 1.


However, setting the scale to 2x is clearer.

So if devicePixelRatio is greater than 1, set it to 3x, otherwise

Set to the defaultPixelScale prop (default: 2x).

```js
new Ruler(...., {
    defaultPixelScale: 1
});
```

**Comment by SidIcarus** [comment]
Thank you!
