### ISSUE TITLE
Option to render selectedRange values

### ISSUE THREAD

**Issue by bytasv** [daybrush/ruler#38]
## Environments
All / latest

## Description
Hey there 👋 I was wondering - how difficult would it be to add values for `selectedRanges` like so (see blue titles on the edge):

<img width="560" alt="CleanShot 2023-01-29 at 14 54 13@2x" src="https://user-images.githubusercontent.com/437214/215327559-d153e3ae-4663-4234-822e-e644bb09a314.png">

Maybe something like this:
- new prop `selectedRangesText={true|false}`
- new prop `selectedRangesTextOffset={[x, y]}` (so to maintain the same API as `textOffset={[x, y]}`
- new prop `selectedRangesTextColor`  (so to maintain the same API as `textColor='#xxx'`

https://github.com/daybrush/ruler/blob/master/packages/react-ruler/src/react-ruler/Ruler.tsx#L206
(I'm not familiar with drawing in canvas, but maybe it would be easy then to draw text on each side of selected range?)

**Comment by daybrush** [comment]
@bytasv 

`ruler`, `guides`'s new version is released. `selectedRangesText`, `selectedRangesTextOffset`, `selectedRangesTextColor` props are added. Try it.
