### ISSUE TITLE
Сan i change the length marks?

### ISSUE THREAD

**Issue by oduvanka** [daybrush/ruler#4]
## Environments
* Framework name: Angular
* Framework version: 8.2
* Component name: ruler
* Component version: 0.2.3
* Testable Address(optional): -

## Description
Hi!
I want the horizontal ruler to have numbers on the bottom.
I want the vertical ruler to have numbers on the right.
![bottom and right rulers](https://user-images.githubusercontent.com/45239739/75632144-51cc6700-5c0a-11ea-8a7a-f9c7ddf3ffac.png)
How can I do it?

**Comment by daybrush** [comment]
@oduvanka 

Thank you :) I'll add this feature.

**Comment by daybrush** [comment]
@oduvanka 

rsion is release. use direction props. (default: "end")

You can direction props to "start"

```js
direction: "start"
```

**Comment by oduvanka** [comment]
Thank you very much!
![Снимок2](https://user-images.githubusercontent.com/45239739/76147531-60a19680-60ae-11ea-9bda-04a4d5d4b921.PNG)
