### ISSUE TITLE
backgroundColor, textColor and lineColor have no effect

### ISSUE THREAD

**Issue by oduvanka** [daybrush/ruler#5]
## Environments
* Framework name: Angular
* Framework version: 8.2
* Component name: ngx-ruler
* Component version: 0.2.3
* Testable Address(optional): https://oduvanka.github.io/checkered-notebook/

## Description
I have component [Ruler](https://github.com/oduvanka/checkered-notebook/tree/with-ruler/src/app/rulers)
I assign values to props "backgroundColor", "textColor" and "lineColor" - [this is in my code](https://github.com/oduvanka/checkered-notebook/blob/29c122b35786dbbe210d94960b5cf7abe629343d/src/app/rulers/rulers.component.ts#L83)
and I pass props to template "rulers.component.html".
In the browser, the ruler does not change color, there are no errors in the console.
Why?

**Comment by jesterstar** [comment]
It`s a good question!

I have another problem. I have a few components with the different colors variant. One of them works fine, but in another component applied only `backgroundColor` property, it looks like `lineColor` and `textColor` does not applied.

**Comment by daybrush** [comment]
@oduvanka @jesterstar 


I'll check it. Thank you :)

**Comment by jesterstar** [comment]
@daybrush FYI!
How about an update to the latest version React lib?
`@scena/react-ruler`
As far as I can see here we have v.0.2.3 and in the react v.0.2.1

**Comment by daybrush** [comment]
@oduvanka 
Different frameworks have different versions.
2.3 is vanilla version.
react version is 2.1.

**Comment by jesterstar** [comment]
@daybrus

> @oduvanka
> Different frameworks have different versions.
> 2.3 is vanilla version.
> react version is 2.1.

Aha, okay, thanks a lot for your explanation!

**Comment by daybrush** [comment]
@oduvanka @jesterstar

ngx-ruler 0.3.0 is released.

Check it agian.

**Comment by oduvanka** [comment]
Ok! :)

![Снимок](https://user-images.githubusercontent.com/45239739/76147411-07853300-60ad-11ea-9ccd-9f50f003c58c.PNG)
