### ISSUE TITLE
how can i change the origin of coordinate

### ISSUE THREAD

**Issue by leeboo** [daybrush/ruler#6]
## Environments
* Framework name: moveable 0.15.1
* Framework version: vue 2.x

## Description
![image](https://user-images.githubusercontent.com/1256745/76673524-04280500-65e1-11ea-8493-8bee87ca3855.png)

**Comment by daybrush** [comment]
use `scrolll` method

`ruler.scroll(-355);` ?

**Comment by leeboo** [comment]
thanks
