### ISSUE TITLE
javascript example

### ISSUE THREAD

**Issue by djmisterjon** [daybrush/ruler#9]
Hi friend, did you have a example of code to use in javascript ?
I trying to make it work, but not succeed.
https://codesandbox.io/s/sad-mendel-wqbtj

**Comment by daybrush** [comment]
@djmisterjon 

0.5.0 is released. Check it again.

**Comment by djmisterjon** [comment]
@daybrush cool, i update the example, work fine 
Here for people want demo, you can fork and add in your wiki if you want
https://codesandbox.io/s/sad-mendel-wqbtj
